name: Hello Agile

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main]

jobs:
  sayHello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello From Github Actions!"